import 'package:flutter_e_commerce/core/localization/app_lang_keys.dart';
Map<String, String> arTr = {
  AppLangKeys.t1	:	"اختر اللغة",
  AppLangKeys.t2	:	"اختر المنتجات",
  AppLangKeys.t3	:	"نحن لدينا 100 الف منتج  , اختر \n  منتجك  من  متجرنا",
  AppLangKeys.t4	:	"سهل وامن للشراء",
  AppLangKeys.t5	:	"يمكنك الدفع كاش او \n من خلال بوابات الدفع الالكترونية",
  AppLangKeys.t6	:	"تتبع طلبك",
  AppLangKeys.t7	:	"يمكنك تتبع طلبك في كل مرحلة \n وايضا التتبع من خلال الخريطة",
  AppLangKeys.t8	:	"متابعه",
  AppLangKeys.t9	:	"تسجيل الدخول",
  AppLangKeys.t10	:	"اهلا بك",
  AppLangKeys.t11	:	"يمكنك تسجيل الدخول من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
  AppLangKeys.t12	:	"ادخل البريد الالكتروني",
  AppLangKeys.t13	:	"ادخل كلمة المرور",
  AppLangKeys.t14	:	"هل نسيت كلمة المرور",
  AppLangKeys.t15	:	"تسجيل الدخول",
  AppLangKeys.t16	:	"ليس لديك حساب ?",
  AppLangKeys.t17	:	"انشاء حساب",
  AppLangKeys.t18	:	"البريد الالكتروني",
  AppLangKeys.t19	:	"كلمة المرور",
  AppLangKeys.t20	:	"اسم المستخدم",
  AppLangKeys.t21	:	"رقم الهاتف",
  AppLangKeys.t22	:	"ادخل رقم الهاتف",
  AppLangKeys.t23	:	"ادخل اسم المستخدم",
  AppLangKeys.t24	:	"انشاء حساب من خلال البريد وكلمة المرور او من خلال وسائل التواصل الاجتماعي",
  AppLangKeys.t25	:	" لديك حساب ?",
  AppLangKeys.t26	:	"تسجيل الدخول",
  AppLangKeys.t27	:	"فحص البريد الالكتروني",
  AppLangKeys.t28	:	"تم انشاء الحساب بنجاح",
  AppLangKeys.t29	:	"الرجاء ادخال البريد لتلقي رمز التحقق",
  AppLangKeys.t30	:	"فحص",
  AppLangKeys.t31	:	"الذهاب لتسجيل الدخول",
  AppLangKeys.t32	:	"نجاح",
  AppLangKeys.t33	:	"حفظ",
  AppLangKeys.t34	:	"الرجاء ادخال كلمة المرور الجديدة",
  AppLangKeys.t35	:	"الكلمة الجديدة",
  AppLangKeys.t36	:	"تم اعادة تعيين كلمة المرور بنجاح",
  AppLangKeys.t37	:	"تهانينا",
  AppLangKeys.t38	:	"تم التسجيل بنجاح",
  AppLangKeys.alreadyHaveAccountSignIn	:	"بالفعل لديك حساب؟ سجل دخول!",
  AppLangKeys.doYouRememberPasswordLogin	:	"هل تتذكر كلمة المرور، سجل دخول",
  AppLangKeys.youCouldCreateNewAccount	:	"يمكنك انشاء حساب جديد",
  AppLangKeys.check	:	"فحص",
  AppLangKeys.checkCode	:	"التأكد من الكود",
  AppLangKeys.pleaseEnterTheDigitCodeSentToEmadgmailcom	:	"من فضلك ادخل الكود المرسل لك علي البريد الإلكتروني.",
  AppLangKeys.checkEmail	:	"التحقق من البريد الالكتروني",
  AppLangKeys.pleaseEnterYourEmailToResetPassword	:	"من فضلك ادخل البريد الالكتروني لاستعادة كلمة المرور.",
  AppLangKeys.confirmPassword	:	"تأكيد كلمة المرور.",
  AppLangKeys.fillTheNewPassword	:	"أدخل كلمة المرور الجديدة",
  AppLangKeys.newPassword	:	"كلمة المرور الجديدة",
  AppLangKeys.requestRestPassword	:	"طلب تعيين كلمة مرور جديدة",
  AppLangKeys.successSignUpYouCanLogInNow	:	"تم إنشاء الحساب بنجاح، يمكنك تسجيل الدخول الأن.",
  AppLangKeys.successResetPasswordUseTheNewPasswordToLogIn	:	"تم تععين كلمة المرور الجديده، قم باستخدمها لتسجيل الدخول.",
  AppLangKeys.thisFieldIsRequired	:	"هذا الحقل مطلوب",
  AppLangKeys.signInWithYourEmailAndPasswordOrContinueWithSocialMedia	:	"سجل دخول باستخدام كلمة المرور او قم باستخدام حسابات التواصل الاجتماعي لتسجيل الدخول.",
  AppLangKeys.welcomeBack	:	"مرحبا بعودتك.",
  AppLangKeys.signIn	:	"تسجيل الدخول",
  AppLangKeys.send	:	"إرسال",
  AppLangKeys.theInputIsRequired	:	"هذا الحقل اجباري",
  AppLangKeys.theMinimumLengthIs	:	" اقل عدد من الحروف هو",
  AppLangKeys.theMaximumLengthIs	:	" أكبر عدد مسموح به من الحروف هو",
  AppLangKeys.notValidEmail	:	"من فضلك ادخل بريد الكتروني صحيح!",
  AppLangKeys.notValidPhone	:	"من فضل ادخل رقم هاتف صحيح",
  AppLangKeys.alarm	:	"تنبية",
  AppLangKeys.doYouExitApp	:	"هل تريد الخروج من التطبيق",
  AppLangKeys.cancel	:	"لا",
  AppLangKeys.thePasswordConfirmationIsWrong	:	"كلمتي المرور غير متطابقتان",
  AppLangKeys.aSummerSurprise	:	"مفاجأة الصيف",
  AppLangKeys.cashback20	:	"كاش باك 20%",
  AppLangKeys.search	:	"ابحث ....",
  AppLangKeys.color	:	"اللون",
  AppLangKeys.red	:	"أحمر",
  AppLangKeys.black	:	"أسود",
  AppLangKeys.blue	:	"أزرق",
  AppLangKeys.disableNotifications	:	"تعطيل الاشعارات",
  AppLangKeys.address	:	"العنوان",
  AppLangKeys.aboutUs	:	"عنا",
  AppLangKeys.contactUs	:	"اتصل بنا",
  AppLangKeys.logOut	:	"تسجيل خروج",
  AppLangKeys.confirm	:	"تأكيد",
  AppLangKeys.price	:	"السعر",
  AppLangKeys.shipping	:	"الشحن",
  AppLangKeys.totalPrice	:	"الإجمالي",
  AppLangKeys.removeFromCart	:	"إزالة من السلة",
  AppLangKeys.addToCart	:	"أضف إلي السلة",
  AppLangKeys.removedFromCart	:	"تم الازالة من السلة",
  AppLangKeys.addedToCart	:	"تم الاضافة إلي السلة",
  AppLangKeys.cartHasBeenUpdated	:	"تم تحديث وحفظ السلة",
  AppLangKeys.alert	:	"اشعار",
  AppLangKeys.codeSuccessfullySent	:	"تم ارسال كود التفعيل",
  AppLangKeys.resendVerificationCode	:	"إعادة إرسال",
  AppLangKeys.myFavorites	:	"المضلات",
  AppLangKeys.addresses	:	"العناوين",
  AppLangKeys.addressesCreate	:	"إنشاء عنوان",
  AppLangKeys.pleaseAllowLocationService	:	"من فضلك فعل خدمة تحديد المواقع!",
  AppLangKeys.pleaseAllowLocationPermissionForTheApp	:	"الرجاء السماح للتطبيق بتحديد الموقع",
  AppLangKeys.continuePress	:	"استمرار",
  AppLangKeys.name	:	"الاسم",
  AppLangKeys.city	:	"المدينة",
  AppLangKeys.street	:	"الشارع",
  AppLangKeys.profile	:	"البروفايل",
  AppLangKeys.cart	:	"السلة",
  AppLangKeys.settings	:	"الاعدادات",
  AppLangKeys.favorite	:	"المفضلة",
  AppLangKeys.myCart	:	"السلة",
  AppLangKeys.coupon	:	"كبون",
  AppLangKeys.apply	:	"تنفيذ",
  AppLangKeys.discount	:	"الخصم",
  AppLangKeys.couponExpired	:	"تم انتهاء الكبون",
  AppLangKeys.couponApplied	:	"تم تطبيق الكبون",
  AppLangKeys.checkout	:	"اعدادات الدفع",
  AppLangKeys.choosePaymentMethod	:	"طريقة الدفع",
  AppLangKeys.cash	:	"نقدي",
  AppLangKeys.cardsPayment	:	"كارت دفع",
  AppLangKeys.chooseDeliveryType	:	"طريقة التوصيل",
  AppLangKeys.shippingAddress	:	"عنوان الشحن",
  AppLangKeys.goToCart	:	"اذهب للسلة",
  AppLangKeys.yourOrderHasBeenRequested	:	"تم تأكيد الطلب، شكرا لك",
  AppLangKeys.pleaseSelectAnAddress	:	"من فضلك اختر عنوان الشحن",
  AppLangKeys.pending : "قيد المراجعة",
  AppLangKeys.underPreparing : "قيد التجهيز",
  AppLangKeys.onTheWay : "في الطريق إليك",
  AppLangKeys.received : "تم التسليم",
  AppLangKeys.archive : "أرشيف",
  AppLangKeys.orders : "الطلبات",
  AppLangKeys.details : "التفاصيل",
  AppLangKeys.orderNumber : "رقم الطلب",
  AppLangKeys.orderType : "نوع الشحن",
  AppLangKeys.orderPrice : "سعر الطلب",
  AppLangKeys.deliveryPrice : "تكلفة الشحن",
  AppLangKeys.paymentMethod : "نوع الدفع",
  AppLangKeys.orderStatus : "حالة الطلب",
  AppLangKeys.delivery : "شحن",
  AppLangKeys.fromStore : "استلام من المخزن",
};
