Map<String, String> enTr = {
  "1": "Choose Language",
  "2": "Choose Product",
  "3":
  "We Have a 100k Product , Choose \n Your Product From  Our \n E-commerce Shop",
  "4": "Easy And Safe Paymnet",
  "5": "You can pay in cash \n or through payment gateways",
  "6": "Track Your Order",
  "7":
  "The order can be tracked at every stage \n until it reaches you",
  "8": "Continue",
  "9": "Sign In",
  "10": "Welcome Back",
  "11":
  "Sign In Your Email And Password Or  Continue With Social Media",
  "12": "Enter Your Email",
  "13": "Enter Your Password",
  "14": "Forget Password",
  "15": "Sign In",
  "16": "Dont Have An Account ? ",
  "17": "Sign Up",
  "18": "Email",
  "19": "Password",
  "20": "Username",
  "21": "Phone",
  "22": "Enter Your Phone",
  "23": "Enter Your Username",
  "24":
  "Sign Up With Your Email And Password OR Continue With Social Media",
  "25": " have an account ? ",
  "26": "SignIn",
  "27": "Check Email",
  "28": "Account successfully created",
  "29": "please Enter Your Email Address To Recive A verification code",
  "30": "check",
  "31": "Go To Login",
  "32": "Success",
  "33": "save",
  "34": "Please Enter new Password",
  "35": "New Password",
  "36": "Password has been reset successfully",
  "37": "congratulations",
  "38": "successfully registered"
};