Map<String, String> enTr = {
  "1": "Choose Language",
  "2": "Choose Product",
  "3":
      "We Have a 100k Product , Choose \n Your Product From  Our \n E-commerce Shop",
  "4": "Easy And Safe Paymnet",
  "5": "You can pay in cash \n or through payment gateways",
  "6": "Track Your Order",
  "7": "The order can be tracked at every stage \n until it reaches you",
  "8": "Continue",
  "9": "Sign In",
  "10": "Welcome Back",
  "11": "Sign In Your Email And Password Or  Continue With Social Media",
  "12": "Enter Your Email",
  "13": "Enter Your Password",
  "14": "Forget Password",
  "15": "Sign In",
  "16": "Dont Have An Account ? ",
  "17": "Sign Up",
  "18": "Email",
  "19": "Password",
  "20": "Username",
  "21": "Phone",
  "22": "Enter Your Phone",
  "23": "Enter Your Username",
  "24": "Sign Up With Your Email And Password OR Continue With Social Media",
  "25": " have an account ? ",
  "26": "SignIn",
  "27": "Check Email",
  "28": "Account successfully created",
  "29": "please Enter Your Email Address To Recive A verification code",
  "30": "check",
  "31": "Go To Login",
  "32": "Success",
  "33": "save",
  "34": "Please Enter new Password",
  "35": "New Password",
  "36": "Password has been reset successfully",
  "37": "congratulations",
  "38": "successfully registered",
  "Already have account? Sign In.": "Already have account? Sign In.",
  "Do you remember password? login.": "Do you remember password? login.",
  "You could create new account": "You could create new account",
  "Check": "Check",
  "Check Code": "Check Code",
  "Please Enter the digit code sent to emad@gmail.com":
      "Please Enter the digit code sent to emad@gmail.com",
  "Check Email": "Check Email",
  "Please enter your email to reset password":
      "Please enter your email to reset password.",
  "Confirm Password": "Confirm Password",
  "Fill the new password": "Fill the new password",
  "New Password": "New Password",
  "Request Rest Password": "Request Rest Password",
  "Success Sign Up, You can log in now": "Success Sign Up, You can log in now",
  "Success Reset Password, Use the new password to log in":
      "Success Reset Password, Use the new password to log in.",
  "This field is required": "This field is required",
  "Sign in with your email and password or continue with social media":
      "Sign in with your email and password or continue with social media",
  "Welcome Back": "Welcome Back",
  "Sign In": "Sign In",
  "Send": "Send",
  "The input is required": "The input is required",
  "The minimum length is ": "The minimum length is ",
  "The maximum length is ": "The maximum length is ",
  "Not valid Email": "Not valid Email",
  "Not valid Phone": "Not valid Phone",
  "Alar": "Alar",
  "Do you exit app": "Do you exit app",
  "Confirm": "Confirm",
  "Cancel": "Cancel",
  "The password confirmation is wrong": "The password confirmation is wrong",
  "A summer surprise": "A summer surprise",
  "Cashback 20%": "Cashback 20%",
  "Search": "Search ...",
  "Color": "Color",

  "Red": "Red",
  "Black": "Black",
  "Blue": "Blue",
  "Add to Cart": "Add to Cart",

  "Disable Notifications": "Disable Notifications",
  "Address": "Address",
  "About Us": "About Us",
  "Contact Us": "Contact Us",
  "Log out": "Log out",
  "Price": "Price",
  "Shipping": "Shipping",
  "Total Price": "Total Price",
  "Remove from Cart": "Remove from Cart",
  "Add To Cart": "Add To Cart",
  "Removed from Cart": "Removed from Cart",
  "Added To Cart": "Added To Cart",
  "Alert":"Alert",
  "Cart has been updated":"Cart has been updated",

  // "":"",
  // "":"",
  // "":"",
  // "":"",
  // "":"",
  // "":"",
  // "":"",
  // "":"",
  // "":"",
  // "":"",
};
