import 'package:flutter_e_commerce/core/localization/app_lang_keys.dart';

Map<String, String> enTr = const {
  AppLangKeys.t1	:	"Choose Language",
  AppLangKeys.t2	:	"Choose Product",
  AppLangKeys.t3	:	"We Have a 100k Product , Choose \n Your Product From  Our \n E-commerce Shop",
  AppLangKeys.t4	:	"Easy And Safe Paymnet",
  AppLangKeys.t5	:	"You can pay in cash \n or through payment gateways",
  AppLangKeys.t6	:	"Track Your Order",
  AppLangKeys.t7	:	"The order can be tracked at every stage \n until it reaches you",
  AppLangKeys.t8	:	"Continue",
  AppLangKeys.t9	:	"Sign In",
  AppLangKeys.t10	:	"Welcome Back",
  AppLangKeys.t11	:	"Sign In Your Email And Password Or  Continue With Social Media",
  AppLangKeys.t12	:	"Enter Your Email",
  AppLangKeys.t13	:	"Enter Your Password",
  AppLangKeys.t14	:	"Forget Password",
  AppLangKeys.t15	:	"Sign In",
  AppLangKeys.t16	:	"Dont Have An Account ?",
  AppLangKeys.t17	:	"Sign Up",
  AppLangKeys.t18	:	"Email",
  AppLangKeys.t19	:	"Password",
  AppLangKeys.t20	:	"Username",
  AppLangKeys.t21	:	"Phone",
  AppLangKeys.t22	:	"Enter Your Phone",
  AppLangKeys.t23	:	"Enter Your Username",
  AppLangKeys.t24	:	"Sign Up With Your Email And Password OR Continue With Social Media",
  AppLangKeys.t25	:	"have an account ?",
  AppLangKeys.t26	:	"SignIn",
  AppLangKeys.t27	:	"Check Email",
  AppLangKeys.t28	:	"Account successfully created",
  AppLangKeys.t29	:	"please Enter Your Email Address To Recive A verification code",
  AppLangKeys.t30	:	"check",
  AppLangKeys.t31	:	"Go To Login",
  AppLangKeys.t32	:	"Success",
  AppLangKeys.t33	:	"save",
  AppLangKeys.t34	:	"Please Enter new Password",
  AppLangKeys.t35	:	"New Password",
  AppLangKeys.t36	:	"Password has been reset successfully",
  AppLangKeys.t37	:	"congratulations",
  AppLangKeys.t38	:	"successfully registered",
  AppLangKeys.alreadyHaveAccountSignIn	:	"Already have account? Sign In.",
  AppLangKeys.doYouRememberPasswordLogin	:	"Do you remember password? login.",
  AppLangKeys.youCouldCreateNewAccount	:	"You could create new account",
  AppLangKeys.check	:	"Check",
  AppLangKeys.checkCode	:	"Check Code",
  AppLangKeys.pleaseEnterTheDigitCodeSentToEmadgmailcom	:	"Please Enter the digit code sent to emad@gmail.com",
  AppLangKeys.checkEmail	:	"Check Email",
  AppLangKeys.pleaseEnterYourEmailToResetPassword	:	"Please enter your email to reset password.",
  AppLangKeys.confirmPassword	:	"Confirm Password",
  AppLangKeys.fillTheNewPassword	:	"Fill the new password",
  AppLangKeys.newPassword	:	"New Password",
  AppLangKeys.requestRestPassword	:	"Request Rest Password",
  AppLangKeys.successSignUpYouCanLogInNow	:	"Success Sign Up, You can log in now",
  AppLangKeys.successResetPasswordUseTheNewPasswordToLogIn	:	"Success Reset Password, Use the new password to log in.",
  AppLangKeys.thisFieldIsRequired	:	"This field is required",
  AppLangKeys.signInWithYourEmailAndPasswordOrContinueWithSocialMedia	:	"Sign in with your email and password or continue with social media",
  AppLangKeys.welcomeBack	:	"Welcome Back",
  AppLangKeys.signIn	:	"Sign In",
  AppLangKeys.send	:	"Send",
  AppLangKeys.theInputIsRequired	:	"The input is required",
  AppLangKeys.theMinimumLengthIs	:	"The minimum length is",
  AppLangKeys.theMaximumLengthIs	:	"The maximum length is",
  AppLangKeys.notValidEmail	:	"Not valid Email",
  AppLangKeys.notValidPhone	:	"Not valid Phone",
  AppLangKeys.alarm	:	"Alarm",
  AppLangKeys.doYouExitApp	:	"Do you exit app",
  AppLangKeys.cancel	:	"Cancel",
  AppLangKeys.thePasswordConfirmationIsWrong	:	"The password confirmation is wrong",
  AppLangKeys.aSummerSurprise	:	"A summer surprise",
  AppLangKeys.cashback20	:	"Cashback 20%",
  AppLangKeys.search	:	"Search ...",
  AppLangKeys.color	:	"Color",
  AppLangKeys.red	:	"Red",
  AppLangKeys.black	:	"Black",
  AppLangKeys.blue	:	"Blue",
  AppLangKeys.disableNotifications	:	"Disable Notifications",
  AppLangKeys.address	:	"Address",
  AppLangKeys.aboutUs	:	"About Us",
  AppLangKeys.contactUs	:	"Contact Us",
  AppLangKeys.logOut	:	"Log out",
  AppLangKeys.confirm	:	"Confirm",
  AppLangKeys.price	:	"Price",
  AppLangKeys.shipping	:	"Shipping",
  AppLangKeys.totalPrice	:	"Total Price",
  AppLangKeys.removeFromCart	:	"Remove from Cart",
  AppLangKeys.addToCart	:	"Add To Cart",
  AppLangKeys.removedFromCart	:	"Removed from Cart",
  AppLangKeys.addedToCart	:	"Added To Cart",
  AppLangKeys.cartHasBeenUpdated	:	"Cart has been updated",
  AppLangKeys.alert	:	"Alert",
  AppLangKeys.codeSuccessfullySent	:	"Code successfully sent",
  AppLangKeys.resendVerificationCode	:	"Resend Code",
  AppLangKeys.myFavorites	:	"My Favorites",
  AppLangKeys.addresses	:	"Addresses",
  AppLangKeys.addressesCreate	:	"Addresses Create",
  AppLangKeys.pleaseAllowLocationService	:	"Please allow location service",
  AppLangKeys.pleaseAllowLocationPermissionForTheApp	:	"Please allow location permission for the app",
  AppLangKeys.continuePress	:	"Continue",
  AppLangKeys.name	:	"name",
  AppLangKeys.city	:	"city",
  AppLangKeys.street	:	"street",
  AppLangKeys.profile	:	"Profile",
  AppLangKeys.cart	:	"Cart",
  AppLangKeys.settings	:	"Settings",
  AppLangKeys.favorite	:	"Favorite",
  AppLangKeys.myCart	:	"My Cart",
  AppLangKeys.coupon	:	"Coupon",
  AppLangKeys.apply	:	"Apply",
  AppLangKeys.discount	:	"Discount",
  AppLangKeys.couponExpired	:	"Coupon Expired",
  AppLangKeys.couponApplied	:	"Coupon Applied",
  AppLangKeys.checkout	:	"Checkout",
  AppLangKeys.choosePaymentMethod	:	"Choose Payment Method",
  AppLangKeys.cash	:	"Cash",
  AppLangKeys.cardsPayment	:	"Cards Payment",
  AppLangKeys.chooseDeliveryType	:	"Choose Delivery Type",
  AppLangKeys.shippingAddress	:	"Shipping Address",
  AppLangKeys.pleaseFillThoseFieldsToCreateNewAccount	:	"PleaseFill those fields to create new account",
  AppLangKeys.goToCart	:	AppLangKeys.goToCart,
  AppLangKeys.yourOrderHasBeenRequested	:	AppLangKeys.yourOrderHasBeenRequested,
  AppLangKeys.pleaseSelectAnAddress	:	AppLangKeys.pleaseSelectAnAddress,
  AppLangKeys.pending : AppLangKeys.pending,
  AppLangKeys.underPreparing : AppLangKeys.underPreparing,
  AppLangKeys.onTheWay : AppLangKeys.onTheWay,
  AppLangKeys.received : AppLangKeys.received,
  AppLangKeys.archive : AppLangKeys.archive,
  AppLangKeys.orders : AppLangKeys.orders,
  AppLangKeys.details : AppLangKeys.details,
  AppLangKeys.orderNumber : AppLangKeys.orderNumber,
  AppLangKeys.orderType : AppLangKeys.orderType,
  AppLangKeys.orderPrice : AppLangKeys.orderPrice,
  AppLangKeys.deliveryPrice : AppLangKeys.deliveryPrice,
  AppLangKeys.paymentMethod : AppLangKeys.paymentMethod,
  AppLangKeys.orderStatus : AppLangKeys.orderStatus,
  AppLangKeys.delivery : AppLangKeys.delivery,
  AppLangKeys.fromStore : AppLangKeys.fromStore,
};
