// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEA81QUlTFVBQXvGdGsBji_ByX2REx0-I',
    appId: '1:323851978658:web:4b95ce82af52d12b0dd4fb',
    messagingSenderId: '323851978658',
    projectId: 'php-flutter-ecommerce',
    authDomain: 'php-flutter-ecommerce.firebaseapp.com',
    storageBucket: 'php-flutter-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3l9fVuvy3apzJikNKLvPis5Rf5cG7wx8',
    appId: '1:323851978658:android:88e58bbc4c7d3b570dd4fb',
    messagingSenderId: '323851978658',
    projectId: 'php-flutter-ecommerce',
    storageBucket: 'php-flutter-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7I4Ab0THOYcSGaoVjVMDg81EhkpOof5M',
    appId: '1:323851978658:ios:deaff993ecbde8360dd4fb',
    messagingSenderId: '323851978658',
    projectId: 'php-flutter-ecommerce',
    storageBucket: 'php-flutter-ecommerce.appspot.com',
    iosClientId:
        '323851978658-j48kpojovkkf2n0lim9qstga8vn6a5rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7I4Ab0THOYcSGaoVjVMDg81EhkpOof5M',
    appId: '1:323851978658:ios:91cd22fca9afbacb0dd4fb',
    messagingSenderId: '323851978658',
    projectId: 'php-flutter-ecommerce',
    storageBucket: 'php-flutter-ecommerce.appspot.com',
    iosClientId:
        '323851978658-jmii7rna4ock0hptgov888fv4uft6nqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterECommerce.RunnerTests',
  );
}
