name: flutter_e_commerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get: ^4.6.5

  # DateTime
  jiffy: ^6.1.0
  intl: ^0.18.0
  http: ^0.13.6

  # Images
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+5

  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.1.0

  # Google Map
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  # Firebase And Notification
  firebase_messaging: ^14.6.0
  firebase_core: ^2.12.0
  flutter_local_notifications: ^14.0.0+2
  cloud_firestore: ^4.7.0

  # Local Data Cache
  sqflite: ^2.2.8+2
  shared_preferences: ^2.1.1
  path: ^1.8.3

  # Qrcode
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.11
  dropdown_search: ^5.0.6
  badges: ^3.1.1

  # Icon
  font_awesome_flutter: ^10.4.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1

  # Google Auth
  google_sign_in: ^6.1.0
  device_preview: ^1.1.0
  responsive_builder: ^0.6.4
  image_pickers: ^2.0.4+1
  flutter_svg: ^2.0.5
  flutter_otp_text_field: ^1.1.1
  lottie: ^2.3.2
  timelines: ^0.1.0
  flutter_ringtone_player: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatar.png
    - assets/lottie/
    - assets/svg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
